### ISSUE TITLE
Unable to destroy plants as active police

### ISSUE THREAD

**Issue by Nathant995** [Project-Sloth/ps-weedplanting#10]
When I attempt to remove plants I get this error;

Invalid Lua type in __data handling line 417 in clientlua of this resource.

DB is connected and is saving plant meta so unsure what's causing this.

**Comment by WildlandsDev** [comment]
further info it seems the error is related to this line of the police destroy function;

   local netId = NetworkGetNetworkIdFromEntity(entity)
