### ISSUE TITLE
Error on sv_planting, line 275

### ISSUE THREAD

**Issue by Kolvicht** [Project-Sloth/ps-weedplanting#2]
if destroying the plant as PD, the fire will throw an error. If you comment out the client event, or get rid of coords on WeedPlants[entity].coords it will skip it, and just delete the plant. 

https://i.imgur.com/qygzYZG.png

**Comment by Smokiiee** [comment]
> if destroying the plant as PD, the fire will throw an error. If you comment out the client event, or get rid of coords on WeedPlants[entity].coords it will skip it, and just delete the plant.
> 
> https://i.imgur.com/qygzYZG.png

did you get this fixed ?

**Comment by MonkeyWhisper** [comment]
Cannot duplicate this, send a video along with error code showing on F8 for testing. I don't know why you will delete lines of codes, they are there for a purpose.

**Comment by Smokiiee** [comment]
> Cannot duplicate this, send a video along with error code showing on F8 for testing. I don't know why you will delete lines of codes, they are there for a purpose.
i did have the same issue but i fixed it by moving the event


https://i.imgur.com/t8V6rR2.png

**Comment by Smokiiee** [comment]
> Cannot duplicate this, send a video along with error code showing on F8 for testing. I don't know why you will delete lines of codes, they are there for a purpose.


i did have the same issue but i fixed it by moving the event


https://i.imgur.com/t8V6rR2.png

**Comment by Lionh34rt** [comment]
https://github.com/Project-Sloth/ps-weedplanting/pull/5
