### ISSUE TITLE
Multiple plants

### ISSUE THREAD

**Issue by Zepherlah** [Project-Sloth/ps-weedplanting#25]
I keep getting multiple plants per seed. E.g If I plant 1x Female seed it plants 2-4 seeds then finishes all in the same location.

Not sure if it's just me I'm going to re download the script and reinstall.

**Comment by Zepherlah** [comment]
If I plant the first 1x Plant. It fine
Second Plant tries to plant 2x Plants
Third Plant Tries to Pplant 3x Plants and so on really odd.

**Comment by MonkeyWhisper** [comment]
Does not happen
