### ISSUE TITLE
Everything works decent expect

### ISSUE THREAD

**Issue by Soldierofthelam** [Project-Sloth/ps-weedplanting#3]
Everything but for deliveries you can't package at the npc no error call up so not sure the issue 
  also polyzones show during delivery and can't get them to shut off causes lag during deliveries with polyzone

![Desktop Screenshot 2023 02 27 - 10 56 47 13](https://user-images.githubusercontent.com/117047687/221614133-f9a473f2-cc0b-4d5d-9342-69c7f501dd29.png)

![Desktop Screenshot 2023 02 27 - 10 53 58 44](https://user-images.githubusercontent.com/117047687/221613039-d4ff5eec-8b5f-4ecc-8e16-2bbbab4a52d6.png)

**Comment by MonkeyWhisper** [comment]
Cannot duplicate, already tested and works fine.

**Comment by Soldierofthelam** [comment]
well for polyzones the code shows


--- Method to create a drop-off location for delivering the weedrun packages
--- @return nil
local createNewDropOff = function()
    if hasDropOff then return end
    hasDropOff = true
    TriggerEvent('qb-phone:client:CustomNotification', _U('weedrun_delivery_title'), _U('weedrun_delivery_godropoff'), 'fas fa-cannabis', '#00FF00', 8000)
    local randomLoc = Shared.DropOffLocations[math.random(#Shared.DropOffLocations)]
    createDropOffBlip(randomLoc)
    dropOffArea = CircleZone:Create(randomLoc.xyz, 85.0, {
		name = 'dropOffArea',
		debugPoly = true   
	})

debugPoly = true   <-----------------"doe's this need to be true to function this is the default"--------------
                                                        "UPDATED TURNING THIS OFF FIXES POLYZONE ISSUE"

it's set to off for packaging

 packageZone = CircleZone:Create(Shared.WeedRunStart.xyz, 10.0, {
                name = 'weedrunning_start',
                debugPoly = false
            })

WEED PACKAGING STILL NOT WORKING WITH NO ERRORS THROWING UP

It' would of been nice if this was actually looked at and not dismissed because you couldn't reproduce the issue,
Everything else works fine in the script but packaging to weedplant_package 
Only way as of right now to use delivery is to spawn in the weedplant_package

**Comment by Soldierofthelam** [comment]
I've spent the day tested this on a new qb-vanilla server build with no other extra scripts except for this one vanilla everything, added items added images same results so I'm not sure how your not able to reproduce this is def not a user error
