### ISSUE TITLE
Water & Feed

### ISSUE THREAD

**Issue by xFluxieDev** [Project-Sloth/ps-weedplanting#4]
I can't feed & give water to the plants.

I got water_bottle in inventory & nothing happens..

**Comment by Smokiiee** [comment]
> I can't feed & give water to the plants.
> 
> I got water_bottle in inventory & nothing happens..

you got some video or something like that on this ?

**Comment by xFluxieDev** [comment]
https://streamable.com/a9hrbj here.

**Comment by Smokiiee** [comment]
> https://streamable.com/a9hrbj here.

is the items in the list in qb-core?

**Comment by xFluxieDev** [comment]
Yes, It works too i just can drink the water & the weed food works to for inhouse planting..

**Comment by Lionh34rt** [comment]
That would imply your HasItem function is returning false/nil

https://github.com/Project-Sloth/ps-weedplanting/blob/main/client/cl_planting.lua#L430
