### ISSUE TITLE
Plants arent disappearing

### ISSUE THREAD

**Issue by NeroThePlayed** [Project-Sloth/ps-weedplanting#47]
Plant props aren't actually getting **removed** when they are destroyed, cleared or harvested
you cant access the plants after they are destroyed or harvested so thats good but its quite annoying to have props everywhere

is there a way we can do so they actually get removed?

From Server Console POV
![image](https://github.com/user-attachments/assets/5ac67974-2b03-466b-89e9-401146e670c3)

From F8 Console
![image](https://github.com/user-attachments/assets/68e13b86-c28a-47b2-b2e6-81c185984486)

Ingame Pov
![image](https://github.com/user-attachments/assets/f64fc451-cc72-4866-be9b-7ca226627b71)

**Comment by FrederikYT** [comment]
it cant be accessed so that is good but the prop stays

**Comment by Lionh34rt** [comment]
The server console error is because you haven't created a weedplanting field in your logs, will look into clearing/harvesting the plants.

@FrederikYT 
Do you have a way to reproduce this 100% of the time?
When updating the script I didn't run into this issue

**Comment by MAGNURIUS** [comment]
The error always occurs, I installed the qb base cleanly, with the relevant dependency on ox_lib, and that's exactly what happens, the props are NOT removed when collected. I checked the Proyect Slot discord, and there are many people who have this problem, a problem that has no answer.

**Comment by Lionh34rt** [comment]
Issue looks resolved to me per https://github.com/Project-Sloth/ps-weedplanting/releases/tag/2.1.1
