### ISSUE TITLE
Planting Weed

### ISSUE THREAD

**Issue by TheCrypticOG** [Project-Sloth/ps-weedplanting#7]
When I go to plant the weed it never actually plants and instead gets frozen on my screen along with the draw text. I cant plant or cancel. This is using the latest version.

https://streamable.com/4h0abw

**Comment by TheCrypticOG** [comment]
So after more testing this issue happens if your not looking at the ground when you use the seed. If you look towards the ground it works fine.

**Comment by MonkeyWhisper** [comment]
Because of range, thanks
